name: Android Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04 # Используем стабильную версию 22.04
    env:
      # Эта переменная окружения может помочь с совместимостью старых рецептов p4a
      BUILD_WITH_OLD_P4A: 1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Buildozer and dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev \
          gettext libgdbm-dev libreadline-dev libbz2-dev sqlite3 libsqlite3-dev \
          tk-dev bzip2 lzma liblzma-dev libgl1-mesa-dev libgles2-mesa-dev patch

          pip install --upgrade pip
          pip install --user "Cython<3.0"  # Установка Cython до Buildozer
          pip install --user sh
          pip install --user "buildozer>=1.5.0"  # Установка Buildozer

      - name: Build with Buildozer
        run: |
          # Указываем Buildozer принимать лицензии SDK автоматически
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WorkTimer-APK
          path: bin/*.apk